travis:
  secure:
    BINSTAR_TOKEN: DPP9yWq/lJz8hHzSTXWohslH/ssOmJLaLF6XGf75uvnyR5FRiQYyB86XAOKhwBTmfg6JWCdBHierqe7fPyyenihnz+sYOq+uEGkY10RLpTlmwQYgJb2U9whJzUqonmcffcBgPYdDi29wecpT4CKelVX3d1OJZD4QaMnq1svxx/dHhQlnTqvkTL5oUuMNRpzSHEGwkdVyYC3yv7vbJu1ZYadke0vMSosA/Iaux+nAgw0fTjpXkRYFgcAr7phyQBTxcQwQOQS5Ty69RvPzcy5TZ4q/8cTmfjistea6/Hp8XYAa7Y+nr497G9BBKGxcc/O+nMpAwLZo73InZvTuP4H0yqYflU5WqrywN6B2Y/zv2KWEo2k12wpWQ96Pny1MXT9RX2uo8dO2wjJdnGKZW43OjHvVSgvQ+TKkszB6dDREJuNK5R9mv5+VePDx3xIdBO3Q7L8Zji/j6scT0Tm88RS5ukKZAWJqArWLlWhoaZm9ZzQTZkAfzwIasphpxf157s5UzEa6LQU91jBbfjWGE3UOf/RZyydMaQIKwQ/ZpY9Sj+PTP4H0he1yIAQd0pXefTxGiFoPWnFnqTRm5zNeZ82AkoBfPq1C/LdGzL7rutSsU03azsc70TFoYCq90GaDf+frXv6j7D3q1zFb+tABgf53TEgVT5+LkXwBbnkyN8Djyc8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
